### ISSUE TITLE
How to use in es6

### ISSUE THREAD

**Issue by hbsoftco** [anodynos/accesscontrol-re#4]
You have explained how to use the package in typescript, Please give an example for those who want to use in es6.

**Comment by anodynos** [comment]
> You have explained how to use the package in typescript, Please give an example for those who want to use in es6.

It's easy to translate TS =-> JS: just remove the `: SomeType` in all expressions like `const someVar: SomeType = someValue;` & `(param: SomeType) => ` and you're left with JS ;-)
