### ISSUE TITLE
* or regexp support in resource

### ISSUE THREAD

**Issue by binarytracer** [anodynos/accesscontrol-re#6]
author @anodynos  thank you for this work.

I would like to ask if you have plan to support resource as the following patterns:
- clients/:id/endpoint-here, as dynamic route in express.
- clients/:id

or may using regexp on the resource?

**Comment by anodynos** [comment]
Hey @binarytracer this library is only a facade to fix issues, no deviating / important features will be added ever :-)

But if you can be patient a few days / weeks, the company I work for (SuperAwesome) we're open sourcing a permissions library for all your needs :-) Underneath it's using accesscontrol & accesscontrol-re but it's a lot more high level and has first class support for resource ownerships ;-) 

It also has native NestJS support (Guards & method decorators) so you're covered :-)

The 1.0 work is done, we're just waiting for clearence. Watch this space permissions.docs.superawesome.com ;-)

**Comment by binarytracer** [comment]
thanks man, @anodynos .

**Comment by anodynos** [comment]
@binarytracer we have released https://github.com/SuperAwesomeLTD/permissions & https://github.com/SuperAwesomeLTD/permissions-nestjs ;-) 

**Note the docs aren't served online yet, you'll need to `$ npm run docs:serve`**

Any comments & contributions more than welcome!

**Comment by binarytracer** [comment]
thanks man, @anodynos.
Im going to check that out.
